apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: robotshop
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
  //
  source:
    repoURL: https://github.com/hara-nobuki-a9n/robot-shop.git
    path: K8s/helm
    targetRevision: master
    helm:
      values: |
        image:
          version: v1.0.0 
